#logging:
#  level.root: "DEBUG"
spring:
  application:
    name: "todopro"
  datasource:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: app_dev
    password: ${DB_PASS}
    url: "jdbc:postgresql://localhost:5432/todo_pro_dev"
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
auth:
  jwks-uri: "http://localhost:9090/.well-known/jwks.json"
