version: "3"
services:
  db:
    networks:
      - appnet
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "app_dev"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data:z
  db-helper:
    networks:
      - appnet
    build:
      context: ./todo-pro-db
    volumes:
      - ./todo-pro-db:/opt/app
    environment:
      NODE_ENV: development
      DB_CONN: ${DB_CONN_APP}
    command: "yarn migrate"
    depends_on:
      - db
  auth-service:
    networks:
      - appnet
    build:
      context: ./auth-service
    ports:
      - "9090:9090"
    environment:
      NODE_ENV: production
      DB_CONN: ${DB_CONN_AUTH}
      AUTH_SERVICE_SECRET: ${AUTH_SERVICE_SECRET}
    command: "yarn serve"
    depends_on:
      - db
  todo-pro-web:
    networks:
      - appnet
    image: rockyj/todo-pro-web:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development # changed in yarn command
    depends_on:
      - auth-service
  todo-pro-api:
    networks:
      - appnet
    image: rockyj/todo-pro-api:latest
    ports:
      - "8080:8080"
    environment:
      DB_PASS: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      - auth-service
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
